services:
    db:
        image: "docker.io/postgres:latest"
        container_name: db
        environment:
            POSTGRES_DB: "gym_db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "admin123"
        volumes:
            - "./db:/var/lib/postgresql/data:rw"
    admin:
        depends_on: "db"
        image: "docker.io/dpage/pgadmin4:latest"
        ports:
            - "25080:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@localhost.net"
            PGADMIN_DEFAULT_PASSWORD: "admin123"
        volumes:
            - "./admin:/var/lib/pgadmin:rw"
